# -*- coding: utf-8 -*-
"""pattern

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7wzdZZ_1TuSJlgAwfB3GWwxBOqN7iKp
"""

n=int(input())
for i in range(0,n):
  for j in range(0,n):
    print("*",end="  ")
  print()

n=int(input())
for i in range(0,n):
  for j in range(i+1):
    print("*",end="  ")
  print()

n=int(input())
for i in range(0,n):
      for j in range(i+1):
        if j%2==0:
          print("*",end=" ")
        else:
          print(j,end=" ")
      print()

n=int(input())
for i in range(1,n+1):
  if i==3:
    pass
  else:
     print(i,end=" ")

n=int(input())
for i in range(i+1):
  for j in range(0,n):
    print("*",end="  ")
  print()

n=int(input())
for i in range(0,n):
 for j in range(i+1):
    print("*",end="   ")
 print()



n=int(input())
for row in range(n):
 for col in range(n):
  ele=(max(row+1 ,col+1,n-row,n-col))
  print(ele,end=" ")
 print()